# System
gpu_num: 0
seed: 42
debug: False
verbose: False

# Train / val
val_size: 0.2

# Data Loader
input_width: 960  #480
input_height: 512 #256
scaler: normalize
num_workers: 4
shuffle: True
drop_last: False

# Model
architecture: DeepLabV3Plus
encoder: timm-efficientnet-b4 #timm-regnety_016
encoder_weight: noisy-student #imagenet
depth: 5
n_classes: 4
activation: null

# Trainer
n_epochs: 40
batch_size: 32
loss: 
  name: MeanCCELoss # MeanCCELoss
  args:
    weight: [1, 1, 1, 1]
metrics: 
  - miou
  - iou1
  - iou2
  - iou3
earlystopping_target: val_miou
earlystopping_patience: 5
optimizer:
  name: AdamW
  args:
    lr: 5.0e-04
    weight_decay: 5.0e-02
scheduler:
  name:  ReduceLROnPlateau
  args:
    factor: 0.2
    mode: 'min'
    patience: 3
    cooldown: 1
# Logging
plot:
  - loss
  - miou
  - iou1
  - iou2
  - iou3
